// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://nhns7lyjgzdjndmm2d6xkevqcu.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bxhkdghczbez3ngpvb7iie6scq",
    "aws_cognito_identity_pool_id": "eu-west-1:9fe6df93-4075-40fb-a4ed-9abdbca9749d",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_Ze7K6BseZ",
    "aws_user_pools_web_client_id": "5di19iop5fre2umvabu0o0tvbd",
    "oauth": {}
};


export default awsmobile;
